server:
  port: ${HTTP_PORT:10010}
theMovieDb:
  ribbon:
    listOfServers: ${themoviedb.baseUrl}
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  file: ${LOG_LOCATION:/var/log/daily-update/${spring.application.name:movie-service}.log}
