server:
  port: ${HTTP_PORT:9000}
#ribbon:
#  eureka:
#    enabled: false
theMovieDb:
  ribbon:
    listOfServers: ${themoviedb.baseUrl}
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  file: ${LOG_LOCATION:/var/log/movie-service.log}
spring:
