spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
      write_dates_with_zone_id: true
      write_null_map_values: false
    deserialization:
      adjust_dates_to_context_time_zone: false

server:
  port: ${PORT}
  contextPath: /travel